version: 2
jobs:
  update_sdk_versions:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # install required apps
      - run: sudo apt-get update
      - run: sudo apt-get install -y jq wget sed git
      
      # install github cli so we can send PRs
      - run: |
          os=$(uname | awk '{print tolower($0)}'); \
          wget --quiet "https://github.com/github/hub/releases/download/v2.12.3/hub-$os-amd64-2.12.3.tgz"; \
          tar -xf hub-$os-amd64-2.12.3.tgz; \
          sudo mv $PWD/hub-$os-amd64-2.12.3/bin/hub /usr/local/bin/hub; \
          rm -rf hub-$os-amd64-2.12.3.tgz; \
          rm -rf $PWD/hub-$os-amd64-2.12.3;
      - run: hub --version

      # add write-enabled deploy key to our machine so we can send PRs
      - add_ssh_keys:
          fingerprints:
            - "0a:d3:a9:32:74:e2:32:24:08:c2:08:0d:c5:89:a8:45"

      - checkout

      # required to push commits
      - run: git config --global user.email "3904043+isen-ng@users.noreply.github.com"
      - run: git config --global user.name "Isen Ng"

      # run with DRY_RUN=false
      - run: ./auto_updater.py --really_push
workflows:
  version: 2
  weekly:
    triggers:
      - schedule:
          # run at 1700UTC (3am +8GMT) every monday
          cron: "0 19 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - update_sdk_versions
  instafix:
    jobs:
      - update_sdk_versions:
          filters:
            tags:
              only: /auto_updater.*/
            branches:
              ignore: /.*/
