name: auto-committer

on:
  schedule:
    # run at 1800UTC (2am +8GMT) and 2000UTC (4am +8GMT) everyday, 1 hour after both auto updaters
    - cron: "0 18,20 * * *"
  workflow_dispatch:
  

jobs:
  commit:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run auto_committer.py
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./auto_committer.py --really_merge
