name: auto-committer

on:
  schedule:
    # run at 1900UTC (3am +8GMT) everyday, 2 hours after auto updater
    - cron: "0 19 * * *"
  workflow_dispatch:
  

jobs:
  commit:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run auto_committer.sh
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./auto_committer.sh false
